/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystems;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mucha
 */
public class ReturnBook extends javax.swing.JFrame {
Connection con=connect.getConnection();
PreparedStatement pst=null;
ResultSet rs=null;

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        txtstudentname = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        txtduedate = new javax.swing.JTextField();
        btnclose = new javax.swing.JButton();
        btnreturn = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("RETURN BOOK DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -10, 490, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("STUDENT ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("BOOK ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 94, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("STUDENT NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("BOOK NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("ISSUE DATE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 140, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("DUE DATE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 120, -1));
        getContentPane().add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 240, 30));
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 240, 30));
        getContentPane().add(txtstudentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 250, 30));
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 240, 30));
        getContentPane().add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 240, 30));
        getContentPane().add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 250, 30));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 30, 41));

        btnreturn.setBackground(new java.awt.Color(153, 0, 0));
        btnreturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreturn.setForeground(new java.awt.Color(255, 255, 255));
        btnreturn.setText("RETURN");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 120, 40));

        btnsearch.setBackground(new java.awt.Color(153, 0, 0));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(242, 242, 242));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 240, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/12.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
            dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
              if(txtstudentid.getText().equals(""))
              {
                  JOptionPane.showMessageDialog(this, "Please enter student id and click on search");
                  txtstudentid.requestFocus();
              }
              else
              {
                  try {
                      pst=con.prepareStatement("select student.name,book.id,book.name,book.issuedate,book.duedate from book inner join student using(id) where book.id=?");
                      pst.setString(1,txtstudentid.getText());
                      rs=pst.executeQuery();
                      if(rs.next())
                      {
                          txtbookid.setText(rs.getString(2));
                          txtstudentname.setText(rs.getString(1));
                          txtduedate.setText(rs.getString(5));
                          txtbookname.setText(rs.getString(3));
                          txtissuedate.setText(rs.getString(4));
                          
                      }
                      else
                      {
                          JOptionPane.showMessageDialog(this,"Please enter valid student id");
                      }
                      
                  } catch (SQLException ex) {
                      Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed

         if(txtstudentid.getText().equals(""))
              {
                  JOptionPane.showMessageDialog(this, "Please enter student id and click on search");
                  txtstudentid.requestFocus();
              }
         else
         {
             try {
                    System.out.println("Book ID: '" + txtbookid.getText() + "'");
                    System.out.println("Student ID: '" + txtstudentid.getText() + "'");
                    System.out.println("Issue Date: '" + txtissuedate.getText() + "'");
                 System.out.println("Due Date: '" + txtduedate.getText() + "'");
                 pst=con.prepareStatement("UPDATE BOOK SET STATUS=?, ISSUEDATE=NULL, DUEDATE=NULL, STUDENTID=NULL WHERE BOOK.ID=?");
                 pst.setString(1,"RETURNED");
                 pst.setString(2,txtbookid.getText());
                 System.out.println("Prepared Statement: " + pst.toString());
                pst.executeUpdate();
               
                 JOptionPane.showMessageDialog(this,"Book Returned");
                 txtissuedate.setText("");
                 txtbookid.setText("");
                 txtbookname.setText("");
                 txtstudentid.setText("");
                 txtstudentname.setText("");
                 txtduedate.setText("");
                 
             } catch (SQLException ex) {
                 Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
             }
         }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtstudentname;
    // End of variables declaration//GEN-END:variables
}
